---
:project:
  :use_exceptions: TRUE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: ./build/ceedling/
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.0
  :default_tasks:
    - test:all

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
  :libraries: []

:defines:
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:flags:
  :common_c_flags: &common_c_flags
    - -Wall
    - -Wextra
    - -pedantic
    - -Wpointer-arith
    - -Wuninitialized
    - -Wcast-align
    - -Wconversion
    - -Wwrite-strings
    - -Wno-comment
    - -Wshadow
    - -Og
    - -g
    - -std=c99
#    - -Wredundant-decls
#    - -Wmissing-declarations
#    - -Werror
  :common_link_flags: &common_link_flags
  :gcov:
    :compile:
      :*:
        - *common_c_flags
    :link:
      :*:
        - *common_link_flags
  :test:
    :compile:
      :*:
        - *common_c_flags
    :link:
      :*:
        - *common_link_flags

:gcov:
  :reports:
    - HtmlDetailed
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90

:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov
...
